import type { Space, TimeSlot } from "../types/booking";

// Generate time slots for the next 7 days
const generateTimeSlots = (basePrice: number): TimeSlot[] => {
  const slots: TimeSlot[] = [];
  const today = new Date();

  for (let day = 0; day < 7; day++) {
    const date = new Date(today);
    date.setDate(today.getDate() + day);
    const dateStr = date.toISOString().split("T")[0];

    // Generate slots from 8 AM to 10 PM (14 hours)
    for (let hour = 8; hour < 22; hour++) {
      const startTime = `${hour.toString().padStart(2, "0")}:00`;
      const endTime = `${(hour + 1).toString().padStart(2, "0")}:00`;

      slots.push({
        date: dateStr,
        startTime,
        endTime,
        isAvailable: Math.random() > 0.3, // 70% availability
        price: basePrice + (hour >= 18 ? 10 : 0), // Higher price after 6 PM
      });
    }
  }

  return slots;
};

export const mockSpaces: Space[] = [
  // SPORT SPACES (10 spaces)
  {
    id: "sport-1",
    name: "KL Badminton Arena",
    type: "sport",
    description:
      "Professional badminton court with premium flooring and lighting. Perfect for tournaments and casual games.",
    images: ["/placeholder-badminton.jpg"],
    location: {
      address: "Jalan Ampang, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.139, lng: 101.6869 },
    },
    amenities: [
      "Air Conditioning",
      "Changing Rooms",
      "Equipment Rental",
      "Parking",
      "Shower Facilities",
    ],
    capacity: 4,
    pricePerHour: 45,
    rating: 4.8,
    reviews: 124,
    availability: generateTimeSlots(45),
  },
  {
    id: "sport-2",
    name: "Elite Futsal Center",
    type: "sport",
    description:
      "Indoor futsal court with FIFA-approved artificial turf and professional goal posts.",
    images: ["/placeholder-futsal.jpg"],
    location: {
      address: "Petaling Jaya, Selangor",
      city: "Petaling Jaya",
      state: "Selangor",
      coordinates: { lat: 3.1073, lng: 101.6421 },
    },
    amenities: [
      "Artificial Turf",
      "Changing Rooms",
      "Ball Rental",
      "Parking",
      "Canteen",
    ],
    capacity: 12,
    pricePerHour: 80,
    rating: 4.7,
    reviews: 89,
    availability: generateTimeSlots(80),
  },
  {
    id: "sport-3",
    name: "Basketball Court Pro",
    type: "sport",
    description:
      "Full-size basketball court with professional hoops and wooden flooring.",
    images: ["/placeholder-basketball.jpg"],
    location: {
      address: "Subang Jaya, Selangor",
      city: "Subang Jaya",
      state: "Selangor",
      coordinates: { lat: 3.0456, lng: 101.5851 },
    },
    amenities: [
      "Professional Court",
      "Ball Rental",
      "Scoreboard",
      "Changing Rooms",
      "Parking",
    ],
    capacity: 10,
    pricePerHour: 60,
    rating: 4.5,
    reviews: 94,
    availability: generateTimeSlots(60),
  },
  {
    id: "sport-4",
    name: "Pickle Ball Paradise",
    type: "sport",
    description:
      "Professional pickle ball courts with premium surface and tournament-grade equipment.",
    images: ["/placeholder-pickleball.jpg"],
    location: {
      address: "Damansara Heights, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1589, lng: 101.6654 },
    },
    amenities: [
      "Professional Courts",
      "Equipment Rental",
      "Changing Rooms",
      "Parking",
      "Shower Facilities",
      "Pro Shop",
    ],
    capacity: 8,
    pricePerHour: 55,
    rating: 4.9,
    reviews: 78,
    availability: generateTimeSlots(55),
  },
  {
    id: "sport-5",
    name: "Tennis Excellence Center",
    type: "sport",
    description:
      "Premium tennis courts with professional coaching available and tournament facilities.",
    images: ["/placeholder-tennis.jpg"],
    location: {
      address: "Mont Kiara, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1726, lng: 101.6507 },
    },
    amenities: [
      "Hard Courts",
      "Ball Machine",
      "Pro Shop",
      "Changing Rooms",
      "Parking",
      "Coaching Available",
    ],
    capacity: 4,
    pricePerHour: 75,
    rating: 4.6,
    reviews: 112,
    availability: generateTimeSlots(75),
  },
  {
    id: "sport-6",
    name: "Squash Masters Arena",
    type: "sport",
    description:
      "Professional squash courts with glass back walls and tournament-grade lighting.",
    images: ["/placeholder-squash.jpg"],
    location: {
      address: "Bangsar, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1285, lng: 101.6671 },
    },
    amenities: [
      "Glass Courts",
      "Equipment Rental",
      "Changing Rooms",
      "Parking",
      "Shower Facilities",
    ],
    capacity: 4,
    pricePerHour: 50,
    rating: 4.4,
    reviews: 67,
    availability: generateTimeSlots(50),
  },
  {
    id: "sport-7",
    name: "Table Tennis Pro",
    type: "sport",
    description:
      "Professional table tennis facility with Olympic-grade tables and coaching services.",
    images: ["/placeholder-tabletennis.jpg"],
    location: {
      address: "Ara Damansara, Petaling Jaya",
      city: "Petaling Jaya",
      state: "Selangor",
      coordinates: { lat: 3.1123, lng: 101.5891 },
    },
    amenities: [
      "Professional Tables",
      "Equipment Rental",
      "Air Conditioning",
      "Parking",
      "Coaching Available",
    ],
    capacity: 8,
    pricePerHour: 35,
    rating: 4.7,
    reviews: 89,
    availability: generateTimeSlots(35),
  },
  {
    id: "sport-8",
    name: "Volleyball Champions",
    type: "sport",
    description:
      "Indoor volleyball courts with professional net systems and tournament facilities.",
    images: ["/placeholder-volleyball.jpg"],
    location: {
      address: "Puchong, Selangor",
      city: "Puchong",
      state: "Selangor",
      coordinates: { lat: 3.0234, lng: 101.6189 },
    },
    amenities: [
      "Professional Courts",
      "Ball Rental",
      "Changing Rooms",
      "Parking",
      "Shower Facilities",
    ],
    capacity: 12,
    pricePerHour: 70,
    rating: 4.5,
    reviews: 76,
    availability: generateTimeSlots(70),
  },
  {
    id: "sport-9",
    name: "Swimming Excellence",
    type: "sport",
    description:
      "Olympic-size swimming pool with professional coaching and lane rental.",
    images: ["/placeholder-swimming.jpg"],
    location: {
      address: "Shah Alam, Selangor",
      city: "Shah Alam",
      state: "Selangor",
      coordinates: { lat: 3.0738, lng: 101.5183 },
    },
    amenities: [
      "Olympic Pool",
      "Lane Rental",
      "Changing Rooms",
      "Shower Facilities",
      "Parking",
      "Coaching Available",
    ],
    capacity: 20,
    pricePerHour: 90,
    rating: 4.8,
    reviews: 145,
    availability: generateTimeSlots(90),
  },
  {
    id: "sport-10",
    name: "Gym & Fitness Studio",
    type: "sport",
    description:
      "Modern fitness studio with professional equipment and personal training services.",
    images: ["/placeholder-gym.jpg"],
    location: {
      address: "Cyberjaya, Selangor",
      city: "Cyberjaya",
      state: "Selangor",
      coordinates: { lat: 2.9186, lng: 101.6561 },
    },
    amenities: [
      "Professional Equipment",
      "Personal Training",
      "Changing Rooms",
      "Shower Facilities",
      "Parking",
      "Sauna",
    ],
    capacity: 15,
    pricePerHour: 40,
    rating: 4.6,
    reviews: 203,
    availability: generateTimeSlots(40),
  },

  // MEETING SPACES (8 spaces)
  {
    id: "meeting-1",
    name: "TechHub Conference Room",
    type: "meeting",
    description:
      "Modern conference room with state-of-the-art AV equipment and video conferencing capabilities.",
    images: ["/placeholder-meeting.jpg"],
    location: {
      address: "KLCC, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1478, lng: 101.6953 },
    },
    amenities: [
      "Video Conferencing",
      "Projector",
      "Whiteboard",
      "WiFi",
      "Coffee Service",
      "Parking",
    ],
    capacity: 16,
    pricePerHour: 120,
    rating: 4.9,
    reviews: 156,
    availability: generateTimeSlots(120),
  },
  {
    id: "meeting-2",
    name: "Executive Boardroom",
    type: "meeting",
    description:
      "Luxury boardroom with premium furnishings and advanced presentation technology.",
    images: ["/placeholder-boardroom.jpg"],
    location: {
      address: "Bangsar South, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1285, lng: 101.6671 },
    },
    amenities: [
      "4K Display",
      "Video Conferencing",
      "Whiteboard",
      "WiFi",
      "Catering Service",
      "Parking",
    ],
    capacity: 12,
    pricePerHour: 150,
    rating: 4.8,
    reviews: 89,
    availability: generateTimeSlots(150),
  },
  {
    id: "meeting-3",
    name: "Creative Workshop Space",
    type: "meeting",
    description:
      "Versatile workshop space perfect for brainstorming sessions and creative meetings.",
    images: ["/placeholder-workshop.jpg"],
    location: {
      address: "Damansara Heights, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1589, lng: 101.6654 },
    },
    amenities: [
      "Interactive Whiteboard",
      "Flip Charts",
      "WiFi",
      "Coffee Service",
      "Parking",
      "Creative Tools",
    ],
    capacity: 20,
    pricePerHour: 100,
    rating: 4.7,
    reviews: 134,
    availability: generateTimeSlots(100),
  },
  {
    id: "meeting-4",
    name: "Training Center Pro",
    type: "meeting",
    description:
      "Professional training facility with classroom setup and multimedia equipment.",
    images: ["/placeholder-training.jpg"],
    location: {
      address: "Petaling Jaya, Selangor",
      city: "Petaling Jaya",
      state: "Selangor",
      coordinates: { lat: 3.1073, lng: 101.6421 },
    },
    amenities: [
      "Projector & Screen",
      "Sound System",
      "WiFi",
      "Coffee Service",
      "Parking",
      "Training Materials",
    ],
    capacity: 25,
    pricePerHour: 110,
    rating: 4.6,
    reviews: 98,
    availability: generateTimeSlots(110),
  },
  {
    id: "meeting-5",
    name: "Interview Suite",
    type: "meeting",
    description:
      "Private interview room with professional setup and recording capabilities.",
    images: ["/placeholder-interview.jpg"],
    location: {
      address: "Mont Kiara, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1726, lng: 101.6507 },
    },
    amenities: [
      "Video Recording",
      "Professional Lighting",
      "WiFi",
      "Coffee Service",
      "Parking",
      "Private Setting",
    ],
    capacity: 6,
    pricePerHour: 80,
    rating: 4.9,
    reviews: 67,
    availability: generateTimeSlots(80),
  },
  {
    id: "meeting-6",
    name: "Presentation Studio",
    type: "meeting",
    description:
      "Professional presentation space with stage and audience seating.",
    images: ["/placeholder-presentation.jpg"],
    location: {
      address: "Subang Jaya, Selangor",
      city: "Subang Jaya",
      state: "Selangor",
      coordinates: { lat: 3.0456, lng: 101.5851 },
    },
    amenities: [
      "Stage Setup",
      "Projector",
      "Sound System",
      "WiFi",
      "Coffee Service",
      "Parking",
    ],
    capacity: 30,
    pricePerHour: 140,
    rating: 4.7,
    reviews: 112,
    availability: generateTimeSlots(140),
  },
  {
    id: "meeting-7",
    name: "Client Meeting Room",
    type: "meeting",
    description:
      "Elegant meeting room perfect for client presentations and business discussions.",
    images: ["/placeholder-client.jpg"],
    location: {
      address: "Ara Damansara, Petaling Jaya",
      city: "Petaling Jaya",
      state: "Selangor",
      coordinates: { lat: 3.1123, lng: 101.5891 },
    },
    amenities: [
      "4K Display",
      "Video Conferencing",
      "WiFi",
      "Coffee Service",
      "Parking",
      "Elegant Furnishings",
    ],
    capacity: 8,
    pricePerHour: 95,
    rating: 4.8,
    reviews: 78,
    availability: generateTimeSlots(95),
  },
  {
    id: "meeting-8",
    name: "Team Collaboration Hub",
    type: "meeting",
    description:
      "Modern collaboration space with flexible seating and interactive technology.",
    images: ["/placeholder-collaboration.jpg"],
    location: {
      address: "Puchong, Selangor",
      city: "Puchong",
      state: "Selangor",
      coordinates: { lat: 3.0234, lng: 101.6189 },
    },
    amenities: [
      "Interactive Displays",
      "Flexible Seating",
      "WiFi",
      "Coffee Service",
      "Parking",
      "Collaboration Tools",
    ],
    capacity: 15,
    pricePerHour: 85,
    rating: 4.5,
    reviews: 92,
    availability: generateTimeSlots(85),
  },

  // COWORKING SPACES (8 spaces)
  {
    id: "coworking-1",
    name: "Creative Coworking Space",
    type: "coworking",
    description:
      "Inspiring coworking environment with hot desks, private pods, and collaborative areas.",
    images: ["/placeholder-coworking.jpg"],
    location: {
      address: "Bangsar, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1285, lng: 101.6671 },
    },
    amenities: [
      "High-Speed WiFi",
      "Printing Services",
      "Coffee Bar",
      "Phone Booths",
      "Networking Events",
    ],
    capacity: 1,
    pricePerHour: 15,
    rating: 4.6,
    reviews: 203,
    availability: generateTimeSlots(15),
  },
  {
    id: "coworking-2",
    name: "Tech Startup Hub",
    type: "coworking",
    description:
      "Modern coworking space designed for tech startups with high-speed internet and meeting rooms.",
    images: ["/placeholder-techhub.jpg"],
    location: {
      address: "Cyberjaya, Selangor",
      city: "Cyberjaya",
      state: "Selangor",
      coordinates: { lat: 2.9186, lng: 101.6561 },
    },
    amenities: [
      "Fiber Internet",
      "Meeting Rooms",
      "Coffee Bar",
      "Phone Booths",
      "Event Space",
      "Parking",
    ],
    capacity: 1,
    pricePerHour: 20,
    rating: 4.8,
    reviews: 167,
    availability: generateTimeSlots(20),
  },
  {
    id: "coworking-3",
    name: "Freelancer's Paradise",
    type: "coworking",
    description:
      "Cozy coworking space perfect for freelancers with quiet zones and networking opportunities.",
    images: ["/placeholder-freelancer.jpg"],
    location: {
      address: "Damansara Heights, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1589, lng: 101.6654 },
    },
    amenities: [
      "Quiet Zones",
      "High-Speed WiFi",
      "Coffee Bar",
      "Printing Services",
      "Networking Events",
      "Parking",
    ],
    capacity: 1,
    pricePerHour: 12,
    rating: 4.5,
    reviews: 145,
    availability: generateTimeSlots(12),
  },
  {
    id: "coworking-4",
    name: "Corporate Coworking",
    type: "coworking",
    description:
      "Professional coworking space with business amenities and executive meeting rooms.",
    images: ["/placeholder-corporate.jpg"],
    location: {
      address: "KLCC, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1478, lng: 101.6953 },
    },
    amenities: [
      "Executive Lounges",
      "Meeting Rooms",
      "High-Speed WiFi",
      "Coffee Service",
      "Reception Services",
      "Parking",
    ],
    capacity: 1,
    pricePerHour: 25,
    rating: 4.9,
    reviews: 234,
    availability: generateTimeSlots(25),
  },
  {
    id: "coworking-5",
    name: "Creative Studio Space",
    type: "coworking",
    description:
      "Artistic coworking environment with creative zones and multimedia facilities.",
    images: ["/placeholder-creative.jpg"],
    location: {
      address: "Petaling Jaya, Selangor",
      city: "Petaling Jaya",
      state: "Selangor",
      coordinates: { lat: 3.1073, lng: 101.6421 },
    },
    amenities: [
      "Creative Zones",
      "Multimedia Equipment",
      "High-Speed WiFi",
      "Coffee Bar",
      "Event Space",
      "Parking",
    ],
    capacity: 1,
    pricePerHour: 18,
    rating: 4.7,
    reviews: 178,
    availability: generateTimeSlots(18),
  },
  {
    id: "coworking-6",
    name: "Green Coworking Hub",
    type: "coworking",
    description:
      "Eco-friendly coworking space with sustainable design and wellness amenities.",
    images: ["/placeholder-green.jpg"],
    location: {
      address: "Mont Kiara, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1726, lng: 101.6507 },
    },
    amenities: [
      "Eco-Friendly Design",
      "Wellness Room",
      "High-Speed WiFi",
      "Organic Coffee",
      "Garden Space",
      "Parking",
    ],
    capacity: 1,
    pricePerHour: 22,
    rating: 4.6,
    reviews: 156,
    availability: generateTimeSlots(22),
  },
  {
    id: "coworking-7",
    name: "24/7 Work Space",
    type: "coworking",
    description:
      "Round-the-clock coworking space with flexible access and night owl amenities.",
    images: ["/placeholder-24-7.jpg"],
    location: {
      address: "Subang Jaya, Selangor",
      city: "Subang Jaya",
      state: "Selangor",
      coordinates: { lat: 3.0456, lng: 101.5851 },
    },
    amenities: [
      "24/7 Access",
      "High-Speed WiFi",
      "Coffee Bar",
      "Quiet Zones",
      "Security System",
      "Parking",
    ],
    capacity: 1,
    pricePerHour: 16,
    rating: 4.4,
    reviews: 134,
    availability: generateTimeSlots(16),
  },
  {
    id: "coworking-8",
    name: "Community Workspace",
    type: "coworking",
    description:
      "Community-focused coworking space with collaborative areas and local business support.",
    images: ["/placeholder-community.jpg"],
    location: {
      address: "Ara Damansara, Petaling Jaya",
      city: "Petaling Jaya",
      state: "Selangor",
      coordinates: { lat: 3.1123, lng: 101.5891 },
    },
    amenities: [
      "Collaborative Areas",
      "High-Speed WiFi",
      "Coffee Bar",
      "Local Business Support",
      "Event Space",
      "Parking",
    ],
    capacity: 1,
    pricePerHour: 14,
    rating: 4.5,
    reviews: 167,
    availability: generateTimeSlots(14),
  },

  // EVENT SPACES (8 spaces)
  {
    id: "event-1",
    name: "Grand Event Hall",
    type: "event",
    description:
      "Spacious event venue perfect for conferences, workshops, and corporate events.",
    images: ["/placeholder-event.jpg"],
    location: {
      address: "Mont Kiara, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1726, lng: 101.6507 },
    },
    amenities: [
      "Stage Setup",
      "Sound System",
      "Lighting",
      "Catering Service",
      "Parking",
      "Security",
    ],
    capacity: 200,
    pricePerHour: 300,
    rating: 4.8,
    reviews: 67,
    availability: generateTimeSlots(300),
  },
  {
    id: "event-2",
    name: "Wedding Palace",
    type: "event",
    description:
      "Elegant wedding venue with beautiful architecture and comprehensive wedding services.",
    images: ["/placeholder-wedding.jpg"],
    location: {
      address: "Bangsar South, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1285, lng: 101.6671 },
    },
    amenities: [
      "Wedding Setup",
      "Catering Service",
      "Photography Areas",
      "Parking",
      "Bridal Suite",
      "Security",
    ],
    capacity: 150,
    pricePerHour: 400,
    rating: 4.9,
    reviews: 89,
    availability: generateTimeSlots(400),
  },
  {
    id: "event-3",
    name: "Corporate Conference Center",
    type: "event",
    description:
      "Professional conference facility with multiple meeting rooms and advanced AV equipment.",
    images: ["/placeholder-conference.jpg"],
    location: {
      address: "KLCC, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1478, lng: 101.6953 },
    },
    amenities: [
      "Multiple Rooms",
      "AV Equipment",
      "Catering Service",
      "WiFi",
      "Parking",
      "Technical Support",
    ],
    capacity: 300,
    pricePerHour: 250,
    rating: 4.7,
    reviews: 123,
    availability: generateTimeSlots(250),
  },
  {
    id: "event-4",
    name: "Art Gallery Events",
    type: "event",
    description:
      "Sophisticated art gallery space perfect for exhibitions, launches, and cultural events.",
    images: ["/placeholder-gallery.jpg"],
    location: {
      address: "Damansara Heights, Kuala Lumpur",
      city: "Kuala Lumpur",
      state: "Selangor",
      coordinates: { lat: 3.1589, lng: 101.6654 },
    },
    amenities: [
      "Gallery Space",
      "Exhibition Setup",
      "Catering Service",
      "Parking",
      "Security",
      "Art Lighting",
    ],
    capacity: 100,
    pricePerHour: 180,
    rating: 4.6,
    reviews: 78,
    availability: generateTimeSlots(180),
  },
  {
    id: "event-5",
    name: "Rooftop Garden Events",
    type: "event",
    description:
      "Stunning rooftop venue with garden setting, perfect for outdoor events and celebrations.",
    images: ["/placeholder-rooftop.jpg"],
    location: {
      address: "Petaling Jaya, Selangor",
      city: "Petaling Jaya",
      state: "Selangor",
      coordinates: { lat: 3.1073, lng: 101.6421 },
    },
    amenities: [
      "Garden Setting",
      "Outdoor Sound System",
      "Catering Service",
      "Parking",
      "Security",
      "Weather Backup",
    ],
    capacity: 120,
    pricePerHour: 220,
    rating: 4.8,
    reviews: 95,
    availability: generateTimeSlots(220),
  },
  {
    id: "event-6",
    name: "Tech Launch Venue",
    type: "event",
    description:
      "Modern tech-focused venue perfect for product launches, hackathons, and tech events.",
    images: ["/placeholder-techlaunch.jpg"],
    location: {
      address: "Cyberjaya, Selangor",
      city: "Cyberjaya",
      state: "Selangor",
      coordinates: { lat: 2.9186, lng: 101.6561 },
    },
    amenities: [
      "Tech Setup",
      "High-Speed WiFi",
      "Catering Service",
      "Parking",
      "Security",
      "Live Streaming",
    ],
    capacity: 80,
    pricePerHour: 200,
    rating: 4.7,
    reviews: 112,
    availability: generateTimeSlots(200),
  },
  {
    id: "event-7",
    name: "Music Performance Hall",
    type: "event",
    description:
      "Acoustic-optimized venue perfect for concerts, performances, and musical events.",
    images: ["/placeholder-music.jpg"],
    location: {
      address: "Subang Jaya, Selangor",
      city: "Subang Jaya",
      state: "Selangor",
      coordinates: { lat: 3.0456, lng: 101.5851 },
    },
    amenities: [
      "Acoustic Design",
      "Professional Sound",
      "Stage Lighting",
      "Catering Service",
      "Parking",
      "Security",
    ],
    capacity: 150,
    pricePerHour: 280,
    rating: 4.9,
    reviews: 67,
    availability: generateTimeSlots(280),
  },
  {
    id: "event-8",
    name: "Community Event Space",
    type: "event",
    description:
      "Versatile community space perfect for local events, workshops, and social gatherings.",
    images: ["/placeholder-community-event.jpg"],
    location: {
      address: "Puchong, Selangor",
      city: "Puchong",
      state: "Selangor",
      coordinates: { lat: 3.0234, lng: 101.6189 },
    },
    amenities: [
      "Flexible Layout",
      "Basic Sound System",
      "Catering Service",
      "Parking",
      "Security",
      "Kitchen Facilities",
    ],
    capacity: 80,
    pricePerHour: 120,
    rating: 4.5,
    reviews: 89,
    availability: generateTimeSlots(120),
  },
];
